const prepath = "https://s3.amazonaws.com/vhyn.dev/images/";

export const tabList = {
  tabs: [
    {
      id: "dioramas",
      title: "Dioramas",
      type: "tab",
      a11yProps: 0,
    },
    {
      id: "necrons",
      title: "Necrons",
      type: "tab",
      a11yProps: 1,
    },
    {
      id: "spaceships",
      title: "Spaceships",
      type: "tab",
      a11yProps: 2,
    },
    {
      id: "otherminis",
      title: "Other Miniatures",
      type: "tab",
      a11yProps: 3,
    },
    {
      id: "otherprojects",
      title: "Other Projects",
      type: "tab",
      a11yProps: 4,
    },
    {
      id: "photography",
      title: "Photography",
      type: "tab",
      a11yProps: 5,
    },
  ],
};

export const tabItems = {
  dioramas: {
    description: undefined,
    a11yProps: 0,
    items: [
      {
        id: "desertDemon",
        type: "tabItem",
        title: "Demon In The Desert",
        display: prepath + "dioramas/desertDemon.jpg",
        images: [
          {
            id: "desertDemon1",
            img: prepath + "dioramas/desertDemon1.jpg",
            alt: "Front view of Demon In The Desert",
            caption: "",
          },
          {
            id: "desertDemon2",
            img: prepath + "dioramas/desertDemon2.jpg",
            alt: "Side view of Demon In The Desert",
            caption: "",
          },
          {
            id: "desertDemon3",
            img: prepath + "dioramas/desertDemon3.jpg",
            alt: "Back view of Demon In The Desert",
            caption: "",
          },
          {
            id: "desertDemon4",
            img: prepath + "dioramas/desertDemon4.jpg",
            alt: "Side view of Demon In The Desert",
            caption: "",
          },
          {
            id: "desertDemon5",
            img: prepath + "dioramas/desertDemon5.jpg",
            alt: "Upper view of Demon In The Desert",
            caption: "",
          },
        ],
      },
      {
        id: "gobbridge",
        type: "tabItem",
        title: "Bridge Goblin",
        display: prepath + "dioramas/gobbridge.jpg",
        images: [
          {
            id: "gobbridge1",
            img: prepath + "dioramas/gobbridge1.jpg",
            alt: "Front view of Bridge Goblin",
            caption: "",
          },
          {
            id: "gobbridge2",
            img: prepath + "dioramas/gobbridge2.jpg",
            alt: "Side view of Bridge Goblin",
            caption: "",
          },
          {
            id: "gobbridge3",
            img: prepath + "dioramas/gobbridge3.jpg",
            alt: "Back view of Bridge Goblin",
            caption: "",
          },
          {
            id: "gobbridge4",
            img: prepath + "dioramas/gobbridge4.jpg",
            alt: "Side view of Bridge Goblin",
            caption: "",
          },
          {
            id: "gobbridge5",
            img: prepath + "dioramas/gobbridge5.jpg",
            alt: "Upper view of Bridge Goblin",
            caption: "",
          },
        ],
      },
    ],
  },
  necrons: {
    description: undefined,
    a11yProps: 1,
    items: [
      {
        id: "nwarriors",
        type: "tabItem",
        title: "Necron Warriors",
        display: prepath + "necrons/nwarriors.jpg",
        images: [
          {
            id: "nwarriors01",
            img: prepath + "necrons/nwarriors01.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors02",
            img: prepath + "necrons/nwarriors02.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors03",
            img: prepath + "necrons/nwarriors03.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors04",
            img: prepath + "necrons/nwarriors04.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors05",
            img: prepath + "necrons/nwarriors05.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors06",
            img: prepath + "necrons/nwarriors06.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors07",
            img: prepath + "necrons/nwarriors07.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors08",
            img: prepath + "necrons/nwarriors08.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors09",
            img: prepath + "necrons/nwarriors09.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors10",
            img: prepath + "necrons/nwarriors10.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors11",
            img: prepath + "necrons/nwarriors11.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors12",
            img: prepath + "necrons/nwarriors12.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nwarriors13",
            img: prepath + "necrons/nwarriors13.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "reanim",
        type: "tabItem",
        title: "Necron Reanimator",
        display: prepath + "necrons/reanim.jpg",
        images: [
          {
            id: "reanim1",
            img: prepath + "necrons/reanim1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reanim2",
            img: prepath + "necrons/reanim2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reanim3",
            img: prepath + "necrons/reanim3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reanim4",
            img: prepath + "necrons/reanim4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "skorpekh",
        type: "tabItem",
        title: "Necron Skorpekh Destroyers",
        display: prepath + "necrons/skorpekh.jpg",
        images: [
          {
            id: "skorpekh01",
            img: prepath + "necrons/skorpekh01.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh02",
            img: prepath + "necrons/skorpekh02.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh03",
            img: prepath + "necrons/skorpekh03.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh04",
            img: prepath + "necrons/skorpekh04.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh05",
            img: prepath + "necrons/skorpekh05.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh06",
            img: prepath + "necrons/skorpekh06.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh07",
            img: prepath + "necrons/skorpekh07.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh08",
            img: prepath + "necrons/skorpekh08.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh09",
            img: prepath + "necrons/skorpekh09.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh10",
            img: prepath + "necrons/skorpekh10.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh11",
            img: prepath + "necrons/skorpekh11.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "skorpekh12",
            img: prepath + "necrons/skorpekh12.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "plascyte",
        type: "tabItem",
        title: "Necron Plasmacyte",
        display: prepath + "necrons/plascyte.jpg",
        images: [
          {
            id: "plascyte4",
            img: prepath + "necrons/plascyte4.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "plascyte1",
            img: prepath + "necrons/plascyte1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "plascyte2",
            img: prepath + "necrons/plascyte2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "plascyte3",
            img: prepath + "necrons/plascyte3.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "crythral",
        type: "tabItem",
        title: "Necron Crypto Thralls",
        display: prepath + "necrons/crythral.jpg",
        images: [
          {
            id: "crythral1",
            img: prepath + "necrons/crythral1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "crythral2",
            img: prepath + "necrons/crythral2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "crythral3",
            img: prepath + "necrons/crythral3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "crythral4",
            img: prepath + "necrons/crythral4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "onwarriors",
        type: "tabItem",
        title: "Necron Warriors Old",
        display: prepath + "necrons/onwarriors.jpg",
        images: [
          {
            id: "onwarriors01",
            img: prepath + "necrons/onwarriors01.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors02",
            img: prepath + "necrons/onwarriors02.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors03",
            img: prepath + "necrons/onwarriors03.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors04",
            img: prepath + "necrons/onwarriors04.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors05",
            img: prepath + "necrons/onwarriors05.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors06",
            img: prepath + "necrons/onwarriors06.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors07",
            img: prepath + "necrons/onwarriors07.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors08",
            img: prepath + "necrons/onwarriors08.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors09",
            img: prepath + "necrons/onwarriors09.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors10",
            img: prepath + "necrons/onwarriors10.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors11",
            img: prepath + "necrons/onwarriors11.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "onwarriors12",
            img: prepath + "necrons/onwarriors12.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "trayn",
        type: "tabItem",
        title: "Trazyn The Infinite",
        display: prepath + "necrons/trayn.jpg",
        images: [
          {
            id: "trayn1",
            img: prepath + "necrons/trayn1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "trayn2",
            img: prepath + "necrons/trayn2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "trayn3",
            img: prepath + "necrons/trayn3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "trayn4",
            img: prepath + "necrons/trayn4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "nmortal",
        type: "tabItem",
        title: "Necron Immortals",
        display: prepath + "necrons/nmortal.jpg",
        images: [
          {
            id: "nmortal1",
            img: prepath + "necrons/nmortal1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nmortal2",
            img: prepath + "necrons/nmortal2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nmortal3",
            img: prepath + "necrons/nmortal3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nmortal4",
            img: prepath + "necrons/nmortal4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "nlord",
        type: "tabItem",
        title: "Necron Lord",
        display: prepath + "necrons/nlord.jpg",
        images: [
          {
            id: "nlord1",
            img: prepath + "necrons/nlord1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nlord2",
            img: prepath + "necrons/nlord2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nlord3",
            img: prepath + "necrons/nlord3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nlord4",
            img: prepath + "necrons/nlord4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
    ],
  },
  spaceships: {
    description: undefined,
    a11yProps: 2,
    items: [
      {
        id: "sphleetFrig",
        type: "tabItem",
        title: "Sphleet Frigate",
        display: prepath + "spaceships/sphleetFrig.jpg",
        images: [
          {
            id: "sphleetFrig1",
            img: prepath + "spaceships/sphleetFrig1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetFrig2",
            img: prepath + "spaceships/sphleetFrig2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetFrig3",
            img: prepath + "spaceships/sphleetFrig3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetFrig4",
            img: prepath + "spaceships/sphleetFrig4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetDrop",
        type: "tabItem",
        title: "Sphleet Dropship",
        display: prepath + "spaceships/sphleetDrop.jpg",
        images: [
          {
            id: "sphleetDrop1",
            img: prepath + "spaceships/sphleetDrop1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetDrop2",
            img: prepath + "spaceships/sphleetDrop2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetDrop3",
            img: prepath + "spaceships/sphleetDrop3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetDrop4",
            img: prepath + "spaceships/sphleetDrop4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetCorvette",
        type: "tabItem",
        title: "Sphleet Corvette",
        display: prepath + "spaceships/sphleetCorvette.jpg",
        images: [
          {
            id: "sphleetCorvette1",
            img: prepath + "spaceships/sphleetCorvette1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetCorvette2",
            img: prepath + "spaceships/sphleetCorvette2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetCorvette3",
            img: prepath + "spaceships/sphleetCorvette3.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetCruiser",
        type: "tabItem",
        title: "Sphleet Cruiser",
        display: prepath + "spaceships/sphleetCruiser.jpg",
        images: [
          {
            id: "sphleetCruiser1",
            img: prepath + "spaceships/sphleetCruiser1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetCruiser2",
            img: prepath + "spaceships/sphleetCruiser2.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetBCruiser",
        type: "tabItem",
        title: "Sphleet Battle Cruiser",
        display: prepath + "spaceships/sphleetBCruiser.jpg",
        images: [
          {
            id: "sphleetBCruiser1",
            img: prepath + "spaceships/sphleetBCruiser1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetBCruiser2",
            img: prepath + "spaceships/sphleetBCruiser2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetBCruiser3",
            img: prepath + "spaceships/sphleetBCruiser3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetBCruiser4",
            img: prepath + "spaceships/sphleetBCruiser4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetLcruiser",
        type: "tabItem",
        title: "Sphleet Light Cruiser",
        display: prepath + "spaceships/sphleetLcruiser.jpg",
        images: [
          {
            id: "sphleetLcruiser1",
            img: prepath + "spaceships/sphleetLcruiser1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetLcruiser2",
            img: prepath + "spaceships/sphleetLcruiser2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetLcruiser3",
            img: prepath + "spaceships/sphleetLcruiser3.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "sphleetBShip",
        type: "tabItem",
        title: "Sphleet Battle Ship",
        display: prepath + "spaceships/sphleetBship.jpg",
        images: [
          {
            id: "sphleetBShip1",
            img: prepath + "spaceships/sphleetBShip1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "sphleetBShip2",
            img: prepath + "spaceships/sphleetBShip2.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
    ],
  },
  otherminis: {
    description: undefined,
    a11yProps: 3,
    items: [
      {
        id: "nurgthirster",
        type: "tabItem",
        title: "Infected Bloodthirster",
        display: prepath + "otherminis/nurgthirster.jpg",
        images: [
          {
            id: "nurgthirster1",
            img: prepath + "otherminis/nurgthirster1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgthirster2",
            img: prepath + "otherminis/nurgthirster2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgthirster3",
            img: prepath + "otherminis/nurgthirster3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgthirster4",
            img: prepath + "otherminis/nurgthirster4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "mimic",
        type: "tabItem",
        title: "Buff Mimic",
        display: prepath + "otherminis/mimic.jpg",
        images: [
          {
            id: "mimic1",
            img: prepath + "otherminis/mimic1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "mimic2",
            img: prepath + "otherminis/mimic2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "mimic3",
            img: prepath + "otherminis/mimic3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "mimic4",
            img: prepath + "otherminis/mimic4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "achRun",
        type: "tabItem",
        title: "ACH! RUN!",
        display: prepath + "otherminis/achRun.jpg",
        images: [
          {
            id: "achRun1",
            img: prepath + "otherminis/achRun1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "achRun2",
            img: prepath + "otherminis/achRun2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "achRun3",
            img: prepath + "otherminis/achRun3.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "nurgle",
        type: "tabItem",
        title: "Lesser Unclean One",
        display: prepath + "otherminis/nurgle.jpg",
        images: [
          {
            id: "nurgle1",
            img: prepath + "otherminis/nurgle1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgle2",
            img: prepath + "otherminis/nurgle2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgle3",
            img: prepath + "otherminis/nurgle3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "nurgle4",
            img: prepath + "otherminis/nurgle4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "gobs",
        type: "tabItem",
        title: "Teal Goblins",
        display: prepath + "otherminis/gobs.jpg",
        images: [
          {
            id: "gobs1",
            img: prepath + "otherminis/gobs1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "gobs2",
            img: prepath + "otherminis/gobs2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "gobs3",
            img: prepath + "otherminis/gobs3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "gobs4",
            img: prepath + "otherminis/gobs4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "greedGobGod",
        type: "tabItem",
        title: "Goblin Incarnate Of Greed",
        display: prepath + "otherminis/greedGobGod.jpg",
        images: [
          {
            id: "greedGobGod1",
            img: prepath + "otherminis/greedGobGod1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "greedGobGod2",
            img: prepath + "otherminis/greedGobGod2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "greedGobGod3",
            img: prepath + "otherminis/greedGobGod3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "greedGobGod4",
            img: prepath + "otherminis/greedGobGod4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "ratScouts",
        type: "tabItem",
        title: "Red Scouts",
        display: prepath + "otherminis/ratScouts.jpg",
        images: [
          {
            id: "ratScouts1",
            img: prepath + "otherminis/ratScouts1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratScouts2",
            img: prepath + "otherminis/ratScouts2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratScouts3",
            img: prepath + "otherminis/ratScouts3.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "ratKing",
        type: "tabItem",
        title: "The Red King",
        display: prepath + "otherminis/ratKing.jpg",
        images: [
          {
            id: "ratKing1",
            img: prepath + "otherminis/ratKing1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKing2",
            img: prepath + "otherminis/ratKing2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKing3",
            img: prepath + "otherminis/ratKing3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKing4",
            img: prepath + "otherminis/ratKing4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "ratKnights",
        type: "tabItem",
        title: "Red King's Guard",
        display: prepath + "otherminis/ratKnights.jpg",
        images: [
          {
            id: "ratKnights1",
            img: prepath + "otherminis/ratKnights1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKnights2",
            img: prepath + "otherminis/ratKnights2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKnights3",
            img: prepath + "otherminis/ratKnights3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratKnights4",
            img: prepath + "otherminis/ratKnights4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "ratPriests",
        type: "tabItem",
        title: "Red Brood Zealots",
        display: prepath + "otherminis/ratPriests.jpg",
        images: [
          {
            id: "ratPriests1",
            img: prepath + "otherminis/ratPriests1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratPriests2",
            img: prepath + "otherminis/ratPriests2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratPriests3",
            img: prepath + "otherminis/ratPriests3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "ratPriests4",
            img: prepath + "otherminis/ratPriests4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
    ],
  },
  otherprojects: {
    description: undefined,
    a11yProps: 4,
    items: [
      {
        id: "meFace",
        type: "tabItem",
        title: "Casting Of My Own Face",
        display: prepath + "otherprojects/meFace.jpg",
        images: [
          {
            id: "meFace1",
            img: prepath + "otherprojects/meFace1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "meFace2",
            img: prepath + "otherprojects/meFace2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "meFace3",
            img: prepath + "otherprojects/meFace3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "meFace4",
            img: prepath + "otherprojects/meFace4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "reaching",
        type: "tabItem",
        title: "Reaching",
        display: prepath + "otherprojects/reaching.jpg",
        images: [
          {
            id: "reaching1",
            img: prepath + "otherprojects/reaching1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reaching2",
            img: prepath + "otherprojects/reaching2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reaching3",
            img: prepath + "otherprojects/reaching3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "reaching4",
            img: prepath + "otherprojects/reaching4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
    ],
  },
  photography: {
    description: undefined,
    a11yProps: 5,
    items: [
      {
        id: "wildFlower",
        type: "tabItem",
        title: "Wild Flowers",
        display: prepath + "photography/wildFlower.jpg",
        images: [
          {
            id: "wildFlower1",
            img: prepath + "photography/wildFlower1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "wildFlower2",
            img: prepath + "photography/wildFlower2.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "wildFlower3",
            img: prepath + "photography/wildFlower3.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "wildFlower4",
            img: prepath + "photography/wildFlower4.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "hBird",
        type: "tabItem",
        title: "Humming Birds",
        display: prepath + "photography/hBird.jpg",
        images: [
          {
            id: "hBird1",
            img: prepath + "photography/hBird1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "hBird2",
            img: prepath + "photography/hBird2.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
      {
        id: "texField",
        type: "tabItem",
        title: "Texas Fields",
        display: prepath + "photography/texField.jpg",
        images: [
          {
            id: "texField1",
            img: prepath + "photography/texField1.jpg",
            alt: "",
            caption: "",
          },
          {
            id: "texField2",
            img: prepath + "photography/texField2.jpg",
            alt: "",
            caption: "",
          },
        ],
      },
    ],
  },
};
